{
  "artifact_3442535765": {
    "java_home": "extracted/jdk-26",
    "java_version_output": "openjdk 26-internal 2026-03-17\nOpenJDK Runtime Environment (build 26-internal-lmesnik-242880c5bbe99280b841a2b5e781f65a96d71af4)\nOpenJDK 64-Bit Server VM (build 26-internal-lmesnik-242880c5bbe99280b841a2b5e781f65a96d71af4, mixed mode, sharing)"
  },
  "status": "passed",
  "history": [
    "a6a9f01c1496ab231d56132cac78d21a7ca03719.json",
    "c7aaa80428c977e932f38bc6d279dc9bf7c21441.json",
    "e1524bbde6687d0662be5243f5faa93673c6ede4.json"
  ],
  "datetime": "2025-07-01T17:02:37.804549+00:00",
  "url": "https://github.com/openjdk/jdk/pull/26031",
  "number": 26031,
  "title": "8359366: RunThese30M.java EXCEPTION_ACCESS_VIOLATION in JvmtiBreakpoints::clearall_in_class_at_safepoint",
  "head_sha": "242880c5bbe99280b841a2b5e781f65a96d71af4",
  "run_url": "https://github.com/dougxc/openjdk-pr-canary/actions/runs/16005164686"
}